//users tableの作成
=>create table users(
	name text not null,
	email text primary key,
	expense integer not null
  );

//products tableの作成
=>create table products(
	name text unique not null,
	price integer not null,
	out_of_stock boolean not null,
	kind kind not null,
	id integer generated by default as identity
  );
//kindの定義
=>create type kind as enum('A', 'B', 'P');


